app:
  build: .
  ports:
    - "8005:8005"
  links:
    - redis_main
    - redis_cache
  env_file:
    - ./setup/docker/envfile.txt

redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-main.conf:/etc/redis/redis.conf

redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./setup/redis/conf/redis-enketo-cache.conf:/etc/redis/redis.conf
